### ISSUE TITLE
Copy-paste from Example-screen doesn't seem to work in Firefox

### ISSUE THREAD

**Issue by andmos** [haavamoa/Gjallarhorn#6]
For some reason I can't copy the example code to the editor in Firefox.

**Comment by haavamoa** [comment]
This has to do with TextArea:disabled. Will take a look at this. Might consider replacing the textarea with a button that paste it in for you.

**Comment by andmos** [comment]
The whole example area can also be removed, with the "edit" screen just showing the example code when empty / entering for the first time 👍

**Comment by haavamoa** [comment]
Good idea :)
